version: "3.5"

services:
  radix-api-contract-testing-dev:
    build:
      context: .
      dockerfile: dev.Dockerfile
    image: radix-api-contract-testing-dev
    container_name: radix-api-contract-testing-dev_container
    command: npm run nodemon
    volumes:
      - type: bind
        source: .
        target: /app
      - type: volume
        source: node-modules
        target: /app/node_modules
      - type: volume
        source: workspace
        target: /app/workspace
    ports:
      - "3000:3000"
      - "9222:9222"

volumes:
  node-modules:
    name: radix-api-contract-testing-dev_node-modules
  workspace:
    name: radix-api-contract-testing-dev_workspace
