apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: radix-api-contract-testing
spec:
  dnsAppAlias:
    environment: prod
    component: server
  environments:
    - name: prod
      build:
        from: master
  components:
    - name: server
      src: "."
      publicPort: http
      environmentConfig:
        - environment: prod
          monitoring: true
          runAsNonRoot: true
      ports:
       - name: http
         port: 8080
      secrets:
        - GITHUB_SHARED_SECRET
